Repository ucl-contoso-chat/ucl-openai-search, pull requests merged in 2024-08, with the labels that each got.

#21 fix: Run repo hooks
  .github/workflows/azure-dev-validation.yaml
  .vscode/tasks.json
  SECURITY.md
  app/frontend/src/assets/github.svg
  app/frontend/src/assets/search.svg
  infra/core/networking/private-dns-zones.bicep
  infra/core/networking/private-endpoint.bicep
  infra/core/networking/vnet.bicep
  infra/core/search/search-services.bicep
  infra/private-endpoints.bicep
Labels: enhancement, good first issue

#31 fix: Handle error message on chat with stream
  app/frontend/src/pages/chat/Chat.tsx
Labels: bug

#28 feat: Add prompt injection protection mechanism
  app/backend/api_wrappers/hugging_face.py
  app/backend/api_wrappers/openai.py
  app/backend/app.py
  app/backend/approaches/chatreadretrieveread.py
  app/backend/approaches/retrievethenread.py
  app/backend/config.py
  app/backend/core/promptprotection.py
  app/backend/error.py
  app/backend/requirements.txt
  app/frontend/src/api/api.ts
  app/frontend/src/api/models.ts
  app/frontend/src/components/ProtectionOptions/ProtectionOptions.tsx
  app/frontend/src/components/ProtectionOptions/index.ts
  app/frontend/src/pages/ask/Ask.tsx
  app/frontend/src/pages/chat/Chat.tsx
  azure.yaml
  infra/main.bicep
  infra/main.parameters.json
  tests/snapshots/test_app/test_ask_handle_exception_contentsafety/client0/result.json
  tests/snapshots/test_app/test_ask_handle_exception_contentsafety/client1/result.json
  tests/snapshots/test_app/test_ask_handle_exception_contextlength/client0/result.json
  tests/snapshots/test_app/test_ask_handle_exception_contextlength/client1/result.json
  tests/snapshots/test_app/test_chat_handle_exception_contentsafety/client0/result.json
  tests/snapshots/test_app/test_chat_handle_exception_contentsafety/client1/result.json
  tests/snapshots/test_app/test_chat_handle_exception_contentsafety_streaming/client0/result.jsonlines
  tests/snapshots/test_app/test_chat_handle_exception_contentsafety_streaming/client1/result.jsonlines
  tests/test_chatapproach.py
Labels: enhancement

#33 ci: Add environment variables for Hugging Face to azure-dev
  .github/workflows/azure-dev.yml
Labels: bug

#32 feat: Add few-shots approach for Phi and OpenAI models
  app/backend/templates/hf_phi3_mini_4k/ask.prompty
  app/backend/templates/openai/ask.prompty
  tests/snapshots/test_app/test_ask_rtr_hybrid/client0/result.json
  tests/snapshots/test_app/test_ask_rtr_hybrid/client1/result.json
  tests/snapshots/test_app/test_ask_rtr_text/client0/result.json
  tests/snapshots/test_app/test_ask_rtr_text/client1/result.json
  tests/snapshots/test_app/test_ask_rtr_text_filter/auth_client0/result.json
  tests/snapshots/test_app/test_ask_rtr_text_filter_public_documents/auth_public_documents_client0/result.json
  tests/snapshots/test_app/test_ask_rtr_text_semanticcaptions/client0/result.json
  tests/snapshots/test_app/test_ask_rtr_text_semanticcaptions/client1/result.json
  tests/snapshots/test_app/test_ask_rtr_text_semanticranker/client0/result.json
  tests/snapshots/test_app/test_ask_rtr_text_semanticranker/client1/result.json
  tests/snapshots/test_app/test_ask_vision/client0/result.json
Labels: bug

#36 docs: adding new templates and protection mechanisms
  CONTRIBUTING.md
  docs/productionizing.md
Labels: documentation

#38 feat: Add tests for available models retrieval
  .gitattributes
  tests/test_supported_models.py
Labels: enhancement
